import { NextRequest, NextResponse } from 'next/server';

const TVSL_KNOWLEDGE = `
TVSL (Tech Valley Solutions Ltd.) is a networking and data center company in Dhaka, Bangladesh.
Website: tvsl-bd.com
Services: Enterprise networking (Cisco/Juniper), Data center solutions, Managed IT services, Fiber connectivity, 24/7 network monitoring.
Open positions: Network Engineer (৳60,000–90,000/mo), Server Administrator (৳55,000–80,000/mo), IT Support Specialist (৳35,000–55,000/mo), Sales Executive (৳40,000–70,000 + commission).
Application process: Apply online → AI-generated technical exam (45 min, 20 questions) → shortlisting → interview → offer.
The AI exam has 15 MCQ and 5 short-answer questions tailored to the specific role.
Location: Dhaka, Bangladesh. Founded 5+ years ago. 200+ enterprise clients. 50+ team members. 99.9% uptime SLA.
CEO: Md Shahrukh Hossain.
Contact: info@tvsl-bd.com
`;

async function geminiChat(message: string, history: Array<{role:string;text:string}>) {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) return null;
  
  const ctx = history.slice(-6).map(m => `${m.role === 'user' ? 'User' : 'Assistant'}: ${m.text}`).join('\n');
  const prompt = `${ctx ? ctx + '\n' : ''}User: ${message}`;
  
  const body = {
    contents: [{ role: 'user', parts: [{ text: prompt }] }],
    systemInstruction: { parts: [{ text: `You are the AI assistant for Tech Valley Solutions Ltd. (TVSL), a networking and data center company in Dhaka, Bangladesh. Use this knowledge:\n${TVSL_KNOWLEDGE}\nBe concise (2-4 sentences), professional, and helpful. If asked something unrelated to TVSL, politely redirect.` }] },
    generationConfig: { temperature: 0.7, maxOutputTokens: 512 },
  };
  
  const res = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`, {
    method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body),
  });
  if (!res.ok) return null;
  const data = await res.json();
  return data.candidates?.[0]?.content?.parts?.[0]?.text || null;
}

function localReply(message: string): string {
  const msg = message.toLowerCase();
  if (msg.includes('service') || msg.includes('offer') || msg.includes('do you'))
    return 'TVSL offers enterprise networking (Cisco/Juniper), data center solutions, managed IT services, and fiber connectivity across Bangladesh. We serve 200+ enterprise clients with 99.9% uptime SLA.';
  if (msg.includes('job') || msg.includes('position') || msg.includes('opening') || msg.includes('hire') || msg.includes('career'))
    return 'We currently have 4 open positions: Network Engineer (৳60–90k/mo), Server Administrator (৳55–80k/mo), IT Support Specialist (৳35–55k/mo), and Sales Executive. Click "Careers" to view details and apply!';
  if (msg.includes('apply') || msg.includes('application') || msg.includes('how to'))
    return 'To apply: go to Careers, select a job, complete the 3-step form (personal info, education, CV upload), then take an AI-generated technical exam. Top scorers are shortlisted for interviews.';
  if (msg.includes('exam') || msg.includes('test') || msg.includes('assessment'))
    return 'The AI exam is 45 minutes long with 20 questions — 15 multiple choice and 5 short-answer questions tailored to the specific role. It\'s auto-generated by Gemini AI and evaluated instantly.';
  if (msg.includes('salary') || msg.includes('pay') || msg.includes('compensation'))
    return 'Salaries range from ৳35,000–৳90,000/month depending on role, plus commission for sales positions. Final offers depend on experience and exam performance.';
  if (msg.includes('location') || msg.includes('where') || msg.includes('office') || msg.includes('address'))
    return 'TVSL is headquartered in Dhaka, Bangladesh. Visit us at tvsl-bd.com or email info@tvsl-bd.com for directions.';
  if (msg.includes('contact') || msg.includes('email') || msg.includes('phone'))
    return 'You can reach TVSL at info@tvsl-bd.com or visit tvsl-bd.com. Our office is in Dhaka, Bangladesh.';
  if (msg.includes('about') || msg.includes('company') || msg.includes('tvsl') || msg.includes('who'))
    return 'Tech Valley Solutions Ltd. (TVSL) is a leading networking and data center company in Bangladesh with 5+ years of experience, serving 200+ enterprise clients with a 50+ member expert team.';
  if (msg.includes('network') || msg.includes('cisco') || msg.includes('router') || msg.includes('switch'))
    return 'TVSL specializes in enterprise networking using Cisco and Juniper equipment — including routing, switching, SD-WAN, firewall management, and 24/7 NOC monitoring for our clients.';
  if (msg.includes('data center') || msg.includes('server') || msg.includes('cloud') || msg.includes('vmware'))
    return 'Our data center services include rack colocation, server management, VMware virtualization, and disaster recovery — all managed by our certified server team.';
  return 'I\'m the TVSL AI assistant! I can help with job openings, our services, the application process, or general company info. What would you like to know?';
}

export async function POST(req: NextRequest) {
  try {
    const { message, history } = await req.json();
    if (!message) return NextResponse.json({ error: 'No message' }, { status: 400 });
    
    // Try Gemini first, fall back to local knowledge base
    const aiReply = await geminiChat(message, history || []).catch(() => null);
    const reply = aiReply || localReply(message);
    
    return NextResponse.json({ reply });
  } catch {
    return NextResponse.json({ reply: "I'm the TVSL assistant! I can help with job openings, services, and company info. What would you like to know?" });
  }
}
