// ============================================================
// Static Data — TVSL Platform
// ============================================================

export const BRAND = "TVSL";

export const JOBS_DATA = [
  {
    id: "j1", title: "Network Engineer", dept: "Networking", type: "Full-time",
    location: "Dhaka, Bangladesh", salary: "৳60,000 – ৳90,000/mo", posted: "2 days ago",
    deadline: "June 30, 2025", examTime: "June 25, 2025 · 10:00 AM", slots: 3,
    tags: ["Cisco", "CCNA", "Routing", "Switching"],
    short: "Design, implement and maintain network infrastructure for our data center clients.",
    requirements: ["3+ years of network engineering experience","CCNA or higher certification","Experience with Cisco, Juniper, or similar","Strong knowledge of TCP/IP, BGP, OSPF","Ability to work on-call rotations"],
    responsibilities: ["Configure and maintain enterprise-grade routers and switches","Monitor network performance and troubleshoot issues","Design network topologies for new client deployments","Document configurations and maintain network diagrams","Collaborate with the server team on data center projects"],
  },
  {
    id: "j2", title: "Server Administrator", dept: "Server", type: "Full-time",
    location: "Dhaka, Bangladesh", salary: "৳55,000 – ৳80,000/mo", posted: "5 days ago",
    deadline: "July 5, 2025", examTime: "June 28, 2025 · 2:00 PM", slots: 2,
    tags: ["Linux", "Windows Server", "VMware", "Docker"],
    short: "Manage and optimize server infrastructure including virtual machines and containers.",
    requirements: ["2+ years in server administration","Linux (RHEL/Ubuntu) expertise","VMware or Hyper-V experience","Basic scripting (Bash or PowerShell)"],
    responsibilities: ["Administer Windows and Linux servers","Manage VMware/vSphere virtual environments","Perform regular backups and disaster recovery testing","Deploy and manage Docker containers","Monitor server health and apply security patches"],
  },
  {
    id: "j3", title: "IT Support Specialist", dept: "IT", type: "Full-time",
    location: "Dhaka, Bangladesh", salary: "৳35,000 – ৳55,000/mo", posted: "1 week ago",
    deadline: "July 10, 2025", examTime: "July 2, 2025 · 11:00 AM", slots: 4,
    tags: ["Help Desk", "Hardware", "Networking", "Support"],
    short: "Provide technical support to internal teams and external clients.",
    requirements: ["1+ year of IT support experience","Hardware and software troubleshooting","Excellent communication skills","A+ or equivalent certification preferred"],
    responsibilities: ["Respond to helpdesk tickets and resolve issues","Set up and configure workstations and peripherals","Assist with network connectivity issues","Maintain IT asset inventory","Document resolutions in the knowledge base"],
  },
  {
    id: "j4", title: "Sales Executive", dept: "Sales & Marketing", type: "Full-time",
    location: "Dhaka, Bangladesh", salary: "৳40,000 – ৳70,000 + commission", posted: "3 days ago",
    deadline: "June 28, 2025", examTime: "June 22, 2025 · 3:00 PM", slots: 2,
    tags: ["B2B Sales", "Networking", "CRM", "Telecom"],
    short: "Drive growth by selling TVSL networking and data center services to businesses.",
    requirements: ["2+ years B2B sales experience","Understanding of networking/IT infrastructure","Strong negotiation skills","CRM experience (Salesforce or similar)"],
    responsibilities: ["Prospect and qualify new enterprise clients","Prepare and deliver technical proposals","Manage the full sales cycle from lead to close","Build and maintain client relationships","Meet monthly and quarterly revenue targets"],
  },
];

export const TEAMS_DATA = [
  {
    id: "networking",
    name: "Network & Cybersecurity",
    icon: "globe",
    color: "var(--primary)",
    lead: { name: "Kishor Kumar Paul", phone: "+88 01708-155713", email: "kishor@tvsl-bd.com" },
    members: [
      { id: "e1", name: "Kishor Kumar Paul", role: "Network Lead", email: "kishor@tvsl-bd.com", phone: "+88 01708-155713", joined: "Jan 2020", skills: ["Cisco", "BGP", "OSPF", "Cybersecurity"] },
      { id: "e2", name: "Fahmida Akter", role: "Network Engineer", email: "fahmida@tvsl-bd.com", phone: "+88 01712-223344", joined: "Aug 2021", skills: ["Routing", "Switching", "VPN"] },
      { id: "e3", name: "Sabbir Hasan", role: "Network Engineer", email: "sabbir@tvsl-bd.com", phone: "+88 01712-334455", joined: "Jan 2022", skills: ["Firewall", "SD-WAN", "Monitoring"] },
      { id: "e4", name: "Lamia Chowdhury", role: "NOC Analyst", email: "lamia@tvsl-bd.com", phone: "+88 01712-445566", joined: "Apr 2022", skills: ["Monitoring", "Alerts", "Reporting"] },
      { id: "e5", name: "Rifat Hossain", role: "Cybersecurity Analyst", email: "rifat@tvsl-bd.com", phone: "+88 01712-556677", joined: "Jun 2022", skills: ["Penetration Testing", "SIEM", "Firewall"] },
      { id: "e6", name: "Nasrin Sultana", role: "Network Technician", email: "nasrin.n@tvsl-bd.com", phone: "+88 01712-667788", joined: "Sep 2022", skills: ["Cabling", "Switches", "Wireless"] },
      { id: "e7", name: "Tanvir Ahmed", role: "Network Technician", email: "tanvir.n@tvsl-bd.com", phone: "+88 01712-778899", joined: "Nov 2022", skills: ["Routing", "VLAN", "Support"] },
      { id: "e8", name: "Mahmudul Hasan", role: "NOC Engineer", email: "mahmudul@tvsl-bd.com", phone: "+88 01712-889900", joined: "Jan 2023", skills: ["Zabbix", "Grafana", "Nagios"] },
      { id: "e9", name: "Sumaiya Akhter", role: "Network Support", email: "sumaiya.n@tvsl-bd.com", phone: "+88 01712-990011", joined: "Mar 2023", skills: ["Help Desk", "L1 Support", "Ticketing"] },
      { id: "e10", name: "Imranul Islam", role: "Junior Network Engineer", email: "imranul@tvsl-bd.com", phone: "+88 01712-001122", joined: "Jun 2023", skills: ["CCNA", "Cisco IOS", "Switching"] },
    ],
  },
  {
    id: "server",
    name: "Server Team",
    icon: "layers",
    color: "var(--success)",
    lead: { name: "Shamir Ashik Chowdhury", phone: "+88 01708-155712", email: "shamir@tvsl-bd.com" },
    members: [
      { id: "s1", name: "Shamir Ashik Chowdhury", role: "Server Lead", email: "shamir@tvsl-bd.com", phone: "+88 01708-155712", joined: "Mar 2020", skills: ["VMware", "Linux", "Storage"] },
      { id: "s2", name: "Roksana Begum", role: "Linux Admin", email: "roksana@tvsl-bd.com", phone: "+88 01720-112233", joined: "Jul 2021", skills: ["RHEL", "Docker", "Kubernetes"] },
      { id: "s3", name: "Shahadat Ullah", role: "Windows Admin", email: "shahadat@tvsl-bd.com", phone: "+88 01720-223344", joined: "Nov 2021", skills: ["AD", "Exchange", "Hyper-V"] },
      { id: "s4", name: "Mitu Akter", role: "Storage Specialist", email: "mitu@tvsl-bd.com", phone: "+88 01720-334455", joined: "Feb 2022", skills: ["SAN", "NAS", "Backup"] },
      { id: "s5", name: "Rafikul Islam", role: "Virtualization Engineer", email: "rafikul@tvsl-bd.com", phone: "+88 01720-445566", joined: "May 2022", skills: ["VMware", "vSphere", "vCenter"] },
      { id: "s6", name: "Jannatul Naim", role: "DevOps Engineer", email: "jannatul.s@tvsl-bd.com", phone: "+88 01720-556677", joined: "Aug 2022", skills: ["Docker", "Kubernetes", "CI/CD"] },
      { id: "s7", name: "Arif Rahman", role: "Backup Engineer", email: "arif.s@tvsl-bd.com", phone: "+88 01720-667788", joined: "Oct 2022", skills: ["Veeam", "Backup", "DR"] },
      { id: "s8", name: "Fatema Begum", role: "Linux Admin", email: "fatema.s@tvsl-bd.com", phone: "+88 01720-778899", joined: "Jan 2023", skills: ["Ubuntu", "CentOS", "Shell"] },
      { id: "s9", name: "Kabir Hossain", role: "Server Technician", email: "kabir.s@tvsl-bd.com", phone: "+88 01720-889900", joined: "Apr 2023", skills: ["Hardware", "BIOS", "RAID"] },
      { id: "s10", name: "Nadia Islam", role: "Junior Admin", email: "nadia.s@tvsl-bd.com", phone: "+88 01720-990011", joined: "Jul 2023", skills: ["Windows Server", "AD", "Support"] },
    ],
  },
  {
    id: "power",
    name: "Power Team",
    icon: "zap",
    color: "var(--warning)",
    lead: { name: "Sofiqur Rahman Shumon", phone: "+88 01711-674351", email: "sofiqur@tvsl-bd.com" },
    members: [
      { id: "p1", name: "Sofiqur Rahman Shumon", role: "Power Team Lead", email: "sofiqur@tvsl-bd.com", phone: "+88 01711-674351", joined: "Feb 2020", skills: ["UPS", "Generator", "Electrical"] },
      { id: "p2", name: "Nazrul Islam", role: "Power Engineer", email: "nazrul@tvsl-bd.com", phone: "+88 01711-112233", joined: "Jun 2021", skills: ["UPS Systems", "PDU", "HVAC"] },
      { id: "p3", name: "Shafiqul Hasan", role: "Electrical Engineer", email: "shafiqul@tvsl-bd.com", phone: "+88 01711-223344", joined: "Sep 2021", skills: ["Wiring", "Panels", "Safety"] },
      { id: "p4", name: "Taslima Khatun", role: "Power Technician", email: "taslima@tvsl-bd.com", phone: "+88 01711-334455", joined: "Jan 2022", skills: ["Generator", "Maintenance", "Testing"] },
      { id: "p5", name: "Rezaur Rahman", role: "UPS Specialist", email: "rezaur@tvsl-bd.com", phone: "+88 01711-445566", joined: "Apr 2022", skills: ["APC", "Eaton", "Battery"] },
      { id: "p6", name: "Monir Hossain", role: "Facilities Technician", email: "monir@tvsl-bd.com", phone: "+88 01711-556677", joined: "Jul 2022", skills: ["HVAC", "Cooling", "Facilities"] },
      { id: "p7", name: "Shapna Akhter", role: "Power Technician", email: "shapna@tvsl-bd.com", phone: "+88 01711-667788", joined: "Nov 2022", skills: ["Electrical", "Safety", "Monitoring"] },
      { id: "p8", name: "Habibur Rahman", role: "Generator Specialist", email: "habibur@tvsl-bd.com", phone: "+88 01711-778899", joined: "Feb 2023", skills: ["Diesel Gen", "Maintenance", "Fuel Mgmt"] },
      { id: "p9", name: "Dilruba Yasmin", role: "Junior Engineer", email: "dilruba@tvsl-bd.com", phone: "+88 01711-889900", joined: "May 2023", skills: ["Electrical", "Wiring", "Safety"] },
      { id: "p10", name: "Kamrul Hasan", role: "Power Technician", email: "kamrul.p@tvsl-bd.com", phone: "+88 01711-990011", joined: "Aug 2023", skills: ["UPS", "Batteries", "Maintenance"] },
    ],
  },
  {
    id: "datacenter",
    name: "Data Center Team",
    icon: "cpu",
    color: "var(--info)",
    lead: { name: "Md. Abdullah Shah", phone: "+88 01730-335897", email: "abdullah@tvsl-bd.com" },
    members: [
      { id: "d1", name: "Md. Abdullah Shah", role: "Data Center Lead", email: "abdullah@tvsl-bd.com", phone: "+88 01730-335897", joined: "Apr 2020", skills: ["DC Ops", "Cabling", "Asset Mgmt"] },
      { id: "d2", name: "Sujon Ahmed", role: "DC Operations", email: "sujon@tvsl-bd.com", phone: "+88 01730-112233", joined: "Aug 2021", skills: ["Rack & Stack", "Cabling", "Patching"] },
      { id: "d3", name: "Nazmul Huda", role: "DC Technician", email: "nazmul@tvsl-bd.com", phone: "+88 01730-223344", joined: "Dec 2021", skills: ["Hardware", "Servers", "Storage"] },
      { id: "d4", name: "Lubna Akhter", role: "Asset Manager", email: "lubna@tvsl-bd.com", phone: "+88 01730-334455", joined: "Mar 2022", skills: ["Inventory", "DCIM", "Asset Tracking"] },
      { id: "d5", name: "Sohel Rana", role: "Colocation Specialist", email: "sohel.d@tvsl-bd.com", phone: "+88 01730-445566", joined: "Jun 2022", skills: ["Colocation", "Client Relations", "SLA"] },
      { id: "d6", name: "Tania Begum", role: "DC Technician", email: "tania.d@tvsl-bd.com", phone: "+88 01730-556677", joined: "Sep 2022", skills: ["Cabling", "Testing", "Documentation"] },
      { id: "d7", name: "Rubel Islam", role: "DC Operations", email: "rubel.d@tvsl-bd.com", phone: "+88 01730-667788", joined: "Dec 2022", skills: ["Physical Security", "Access Control", "Monitoring"] },
      { id: "d8", name: "Sharmin Akter", role: "Junior Technician", email: "sharmin.d@tvsl-bd.com", phone: "+88 01730-778899", joined: "Mar 2023", skills: ["Rack", "Hardware", "Support"] },
      { id: "d9", name: "Milon Hossain", role: "DC Coordinator", email: "milon@tvsl-bd.com", phone: "+88 01730-889900", joined: "Jun 2023", skills: ["Coordination", "Documentation", "Reporting"] },
      { id: "d10", name: "Poly Khatun", role: "Junior Technician", email: "poly@tvsl-bd.com", phone: "+88 01730-990011", joined: "Sep 2023", skills: ["Cabling", "Patching", "Labeling"] },
    ],
  },
  {
    id: "it",
    name: "IT Team",
    icon: "shield",
    color: "oklch(0.52 0.14 230)",
    lead: { name: "A M Rashid Ashef Hossain", phone: "+88 01711-000000", email: "rashid@tvsl-bd.com" },
    members: [
      { id: "i1", name: "A M Rashid Ashef Hossain", role: "IT Manager", email: "rashid@tvsl-bd.com", phone: "+88 01711-000000", joined: "Jan 2022", skills: ["Network Admin", "Security", "Linux"] },
      { id: "i2", name: "Nusrat Jahan", role: "IT Specialist", email: "nusrat@tvsl-bd.com", phone: "+88 01711-223344", joined: "Mar 2022", skills: ["Help Desk", "Hardware", "Windows"] },
      { id: "i3", name: "Tanvir Ahmed", role: "Systems Analyst", email: "tanvir.it@tvsl-bd.com", phone: "+88 01711-334455", joined: "Jun 2022", skills: ["Analysis", "Documentation", "Scripting"] },
      { id: "i4", name: "Sadia Hossain", role: "IT Support", email: "sadia@tvsl-bd.com", phone: "+88 01711-445566", joined: "Sep 2022", skills: ["Support", "Troubleshooting", "Ticketing"] },
      { id: "i5", name: "Mahfuz Alam", role: "IT Support", email: "mahfuz.it@tvsl-bd.com", phone: "+88 01711-556677", joined: "Dec 2022", skills: ["Hardware", "Software", "Help Desk"] },
      { id: "i6", name: "Rima Akter", role: "System Admin", email: "rima.it@tvsl-bd.com", phone: "+88 01711-667788", joined: "Feb 2023", skills: ["Windows", "Active Directory", "GPO"] },
      { id: "i7", name: "Shakil Ahmed", role: "IT Technician", email: "shakil.it@tvsl-bd.com", phone: "+88 01711-778899", joined: "May 2023", skills: ["Hardware", "Networking", "Support"] },
      { id: "i8", name: "Priya Das", role: "Junior IT Support", email: "priya.it@tvsl-bd.com", phone: "+88 01711-889900", joined: "Aug 2023", skills: ["Ticketing", "Desktop Support", "MS Office"] },
    ],
  },
  {
    id: "sales",
    name: "Sales & Marketing",
    icon: "chartLine",
    color: "var(--danger)",
    lead: { name: "Raihan Kabir", phone: "+88 01722-112233", email: "raihan@tvsl-bd.com" },
    members: [
      { id: "m1", name: "Raihan Kabir", role: "Sales Manager", email: "raihan@tvsl-bd.com", phone: "+88 01722-112233", joined: "May 2021", skills: ["B2B Sales", "Negotiation", "CRM"] },
      { id: "m2", name: "Jannatul Ferdous", role: "Marketing Executive", email: "jannatul@tvsl-bd.com", phone: "+88 01722-223344", joined: "Aug 2021", skills: ["Social Media", "Content", "SEO"] },
      { id: "m3", name: "Mahbub Alam", role: "Sales Executive", email: "mahbub@tvsl-bd.com", phone: "+88 01722-334455", joined: "Oct 2021", skills: ["Lead Gen", "Cold Calling", "Proposals"] },
      { id: "m4", name: "Popy Akter", role: "Brand Specialist", email: "popy@tvsl-bd.com", phone: "+88 01722-445566", joined: "Jan 2022", skills: ["Branding", "Design", "Campaigns"] },
      { id: "m5", name: "Shamsul Huda", role: "Sales Executive", email: "shamsul@tvsl-bd.com", phone: "+88 01722-556677", joined: "Mar 2022", skills: ["Enterprise Sales", "BD", "Proposals"] },
      { id: "m6", name: "Farzana Khatun", role: "Digital Marketing", email: "farzana.m@tvsl-bd.com", phone: "+88 01722-667788", joined: "Jun 2022", skills: ["Google Ads", "Meta Ads", "Analytics"] },
      { id: "m7", name: "Ruhul Amin", role: "Sales Executive", email: "ruhul.m@tvsl-bd.com", phone: "+88 01722-778899", joined: "Sep 2022", skills: ["SME Sales", "Telco", "Client Mgmt"] },
      { id: "m8", name: "Tamanna Begum", role: "Content Creator", email: "tamanna.m@tvsl-bd.com", phone: "+88 01722-889900", joined: "Dec 2022", skills: ["Content Writing", "Social Media", "PR"] },
      { id: "m9", name: "Ariful Islam", role: "Junior Sales", email: "ariful.m@tvsl-bd.com", phone: "+88 01722-990011", joined: "Mar 2023", skills: ["Cold Calling", "Lead Gen", "CRM"] },
      { id: "m10", name: "Nishat Ara", role: "Marketing Intern", email: "nishat.m@tvsl-bd.com", phone: "+88 01722-001122", joined: "Jun 2023", skills: ["Social Media", "Content", "Research"] },
    ],
  },
  {
    id: "management",
    name: "Management",
    icon: "briefcase",
    color: "oklch(0.45 0.14 300)",
    lead: { name: "Mohammad Mahfuz Ali Sohel", phone: "+88 01700-000001", email: "chairman@tvsl-bd.com" },
    members: [
      { id: "mg1", name: "Mohammad Mahfuz Ali Sohel", role: "Chairman", email: "chairman@tvsl-bd.com", phone: "+88 01700-000001", joined: "Jan 2019", skills: ["Strategy", "Leadership", "Business Dev"] },
      { id: "mg2", name: "Mohammad Amir Hassan Chowdhury", role: "Head of HR & Admin", email: "hr@tvsl-bd.com", phone: "+88 01700-000002", joined: "Mar 2019", skills: ["HR", "Recruitment", "Compliance"] },
      { id: "mg3", name: "Imran Hossain", role: "Finance Manager", email: "finance@tvsl-bd.com", phone: "+88 01700-000003", joined: "Jun 2019", skills: ["Accounting", "Payroll", "Audit"] },
      { id: "mg4", name: "Sumaiya Nasrin", role: "Operations Manager", email: "ops@tvsl-bd.com", phone: "+88 01700-000004", joined: "Jan 2020", skills: ["Operations", "Project Mgmt", "Vendor"] },
      { id: "mg5", name: "Sharif Hossain", role: "Business Dev Manager", email: "biz@tvsl-bd.com", phone: "+88 01700-000005", joined: "Apr 2020", skills: ["BD", "Partnerships", "Strategy"] },
    ],
  },
];

export const APPLICANTS_DATA = [
  { id: "a1", name: "Abu Sayeed", email: "abu@email.com", jobId: "j1", jobTitle: "Network Engineer", score: 87, status: "shortlisted", appliedDate: "2 days ago", skills: ["Cisco", "CCNA", "BGP"], education: "BSc Computer Science, BUET", experience: "4 years" },
  { id: "a2", name: "Naima Islam", email: "naima@email.com", jobId: "j1", jobTitle: "Network Engineer", score: 74, status: "pending", appliedDate: "3 days ago", skills: ["Routing", "Switching", "Linux"], education: "BSc EEE, KUET", experience: "2 years" },
  { id: "a3", name: "Farhan Haque", email: "farhan@email.com", jobId: "j2", jobTitle: "Server Administrator", score: 91, status: "shortlisted", appliedDate: "1 day ago", skills: ["VMware", "Docker", "Linux"], education: "BSc CSE, DIU", experience: "5 years" },
  { id: "a4", name: "Tania Sultana", email: "tania@email.com", jobId: "j3", jobTitle: "IT Support Specialist", score: 62, status: "pending", appliedDate: "5 days ago", skills: ["Help Desk", "Hardware", "Windows"], education: "Diploma in ICT", experience: "1 year" },
  { id: "a5", name: "Rezaul Karim", email: "reza@email.com", jobId: "j4", jobTitle: "Sales Executive", score: 78, status: "interview", appliedDate: "4 days ago", skills: ["B2B Sales", "Negotiation", "CRM"], education: "BBA Marketing, IBA", experience: "3 years" },
];

export const NOTICES_DATA = [
  { id: "n1", title: "Q2 Performance Review", body: "Q2 performance reviews will begin on June 20. All team leads should submit their team reports by June 18.", date: "June 10, 2025", type: "meeting", priority: "high" },
  { id: "n2", title: "Network Maintenance Window", body: "Scheduled downtime for core switch upgrade: Saturday June 14, 12:00 AM – 4:00 AM. All services will be unavailable.", date: "June 8, 2025", type: "work", priority: "high" },
  { id: "n3", title: "New Client Onboarding — Apex Corporation", body: "We have successfully onboarded Apex Corporation as a new enterprise client. The networking and server teams should review the SLA document.", date: "June 6, 2025", type: "company", priority: "medium" },
  { id: "n4", title: "EID Holiday Notice", body: "The office will be closed June 17–20 for Eid al-Adha. Emergency support remains active via the on-call rotation.", date: "June 4, 2025", type: "company", priority: "low" },
];
